import 'package:flutter/material.dart';
import '../../model/GameConsole.dart';
import 'GameConsoleGridWidget.dart';
import '../../state/AppState.dart';

class GameConsolePage extends StatelessWidget {
  const GameConsolePage({super.key});

  @override
  Widget build(BuildContext context) {
    final appState = AppState.of(context);
    return Stack(
      children: [
        GameConsoleGridWidget(
          gameConsoleList: gameConsoleList,
          gridColumnCount: appState.gridColumnCount,
        ),
        Positioned(
          right: 16,
          bottom: 16,
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.grey.shade300),
            ),
            padding: const EdgeInsets.all(10),
            child: Row(
              children: [
                IconButton(
                  onPressed: appState.decrementGridColumnCount,
                  icon: const Icon(Icons.remove),
                ),
                IconButton(
                  onPressed: appState.incrementGridColumnCount,
                  icon: const Icon(Icons.add),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

const List<GameConsole> gameConsoleList = [
  GameConsole(title: 'ADVMAME', image: 'ADVMAME.png', description: ''),
  GameConsole(title: 'AMIGA', image: 'AMIGA.png', description: ''),
  GameConsole(title: 'AMIGACD', image: 'AMIGACD.png', description: ''),
  GameConsole(title: 'AMIGACDTV', image: 'AMIGACDTV.png', description: ''),
  GameConsole(title: 'ARCADE', image: 'ARCADE.png', description: ''),
  GameConsole(title: 'ARCADE_FBNEO', image: 'ARCADE_FBNEO.png', description: ''),
  GameConsole(title: 'ARDUBOY', image: 'ARDUBOY.png', description: ''),
  GameConsole(title: 'ATARI2600', image: 'ATARI2600.png', description: ''),
  GameConsole(title: 'ATARI5200', image: 'ATARI5200.png', description: ''),
  GameConsole(title: 'ATARI7800', image: 'ATARI7800.png', description: ''),
  GameConsole(title: 'ATARI800', image: 'ATARI800.png', description: ''),
  GameConsole(title: 'ATARI800-alt', image: 'ATARI800-alt.png', description: ''),
  GameConsole(title: 'ATARIST', image: 'ATARIST.png', description: ''),
  GameConsole(title: 'ATOMISWAVE', image: 'ATOMISWAVE.png', description: ''),
  GameConsole(title: 'C64', image: 'C64.png', description: ''),
  GameConsole(title: 'CANNONBALL', image: 'CANNONBALL.png', description: ''),
  GameConsole(title: 'CAVESTORY', image: 'CAVESTORY.png', description: ''),
  GameConsole(title: 'CHAILOVE', image: 'CHAILOVE.png', description: ''),
  GameConsole(title: 'CHANNELF', image: 'CHANNELF.png', description: ''),
  GameConsole(title: 'COLECO', image: 'COLECO.png', description: ''),
  GameConsole(title: 'COLSGM', image: 'COLSGM.png', description: ''),
  GameConsole(title: 'CPC', image: 'CPC.png', description: ''),
  GameConsole(title: 'cpc-alt', image: 'cpc-alt.png', description: ''),
  GameConsole(title: 'CPET', image: 'CPET.png', description: ''),
  GameConsole(title: 'CPLUS4', image: 'CPLUS4.png', description: ''),
  GameConsole(title: 'CPS1', image: 'CPS1.png', description: ''),
  GameConsole(title: 'CPS2', image: 'CPS2.png', description: ''),
  GameConsole(title: 'CPS3', image: 'CPS3.png', description: ''),
  GameConsole(title: 'DAPHNE', image: 'DAPHNE.png', description: ''),
  GameConsole(title: 'DC', image: 'DC.png', description: ''),
  GameConsole(title: 'DINOTHAWR', image: 'DINOTHAWR.png', description: ''),
  GameConsole(title: 'DOOM', image: 'DOOM.png', description: ''),
  GameConsole(title: 'DOS', image: 'DOS.png', description: ''),
  GameConsole(title: 'EASYRPG', image: 'EASYRPG.png', description: ''),
  GameConsole(title: 'ENTERPRISE', image: 'ENTERPRISE.png', description: ''),
  GameConsole(title: 'FBNEO', image: 'FBNEO.png', description: ''),
  GameConsole(title: 'FC', image: 'FC.png', description: ''),
  GameConsole(title: 'FDS', image: 'FDS.png', description: ''),
  GameConsole(title: 'FLASHBACK', image: 'FLASHBACK.png', description: ''),
  GameConsole(title: 'GB', image: 'GB.png', description: ''),
  GameConsole(title: 'GBA', image: 'GBA.png', description: ''),
  GameConsole(title: 'GBC', image: 'GBC.png', description: ''),
  GameConsole(title: 'GG', image: 'GG.png', description: ''),
  GameConsole(title: 'GW', image: 'GW.png', description: ''),
  GameConsole(title: 'INTELLIVISION', image: 'INTELLIVISION.png', description: ''),
  GameConsole(title: 'LOWRESNX', image: 'LOWRESNX.png', description: ''),
  GameConsole(title: 'LUTRO', image: 'LUTRO.png', description: ''),
  GameConsole(title: 'LYNX', image: 'LYNX.png', description: ''),
  GameConsole(title: 'MAME', image: 'MAME.png', description: ''),
  GameConsole(title: 'MAME2003PLUS', image: 'MAME2003PLUS.png', description: ''),
  GameConsole(title: 'MAME2010', image: 'MAME2010.png', description: ''),
  GameConsole(title: 'MD', image: 'MD.png', description: ''),
  GameConsole(title: 'MDMSU', image: 'MDMSU.png', description: ''),
  GameConsole(title: 'MEGADUCK', image: 'MEGADUCK.png', description: ''),
  GameConsole(title: 'MS', image: 'MS.png', description: ''),
  GameConsole(title: 'MSX', image: 'MSX.png', description: ''),
  GameConsole(title: 'MSX2', image: 'MSX2.png', description: ''),
  GameConsole(title: 'N64', image: 'N64.png', description: ''),
  GameConsole(title: 'N64DD', image: 'N64DD.png', description: ''),
  GameConsole(title: 'NAOMI', image: 'NAOMI.png', description: ''),
  GameConsole(title: 'NDS', image: 'NDS.png', description: ''),
  GameConsole(title: 'NEOCD', image: 'NEOCD.png', description: ''),
  GameConsole(title: 'NEOGEO', image: 'NEOGEO.png', description: ''),
  GameConsole(title: 'NGC', image: 'NGC.png', description: ''),
  GameConsole(title: 'NGP', image: 'NGP.png', description: ''),
  GameConsole(title: 'OPENBOR', image: 'OPENBOR.png', description: ''),
  GameConsole(title: 'PALMOS', image: 'PALMOS.png', description: ''),
  GameConsole(title: 'PANASONIC', image: 'PANASONIC.png', description: ''),
  GameConsole(title: 'PC88', image: 'PC88.png', description: ''),
  GameConsole(title: 'PC98', image: 'PC98.png', description: ''),
  GameConsole(title: 'PCE', image: 'PCE.png', description: ''),
  GameConsole(title: 'PCECD', image: 'PCECD.png', description: ''),
  GameConsole(title: 'PCFX', image: 'PCFX.png', description: ''),
  GameConsole(title: 'PGM', image: 'PGM.png', description: ''),
  GameConsole(title: 'PICO', image: 'PICO.png', description: ''),
  GameConsole(title: 'POKEMINI', image: 'POKEMINI.png', description: ''),
  GameConsole(title: 'PORTS', image: 'PORTS.png', description: ''),
  GameConsole(title: 'PS', image: 'PS.png', description: ''),
  GameConsole(title: 'PSP', image: 'PSP.png', description: ''),
  GameConsole(title: 'PSPMINIS', image: 'PSPMINIS.png', description: ''),
  GameConsole(title: 'SATELLAVIEW', image: 'SATELLAVIEW.png', description: ''),
  GameConsole(title: 'SATURN', image: 'SATURN.png', description: ''),
  GameConsole(title: 'SCUMMVM', image: 'SCUMMVM.png', description: ''),
  GameConsole(title: 'SEGA32X', image: 'SEGA32X.png', description: ''),
  GameConsole(title: 'SEGACD', image: 'SEGACD.png', description: ''),
  GameConsole(title: 'SFC', image: 'SFC.png', description: ''),
  GameConsole(title: 'SFCMSU', image: 'SFCMSU.png', description: ''),
  GameConsole(title: 'SFX', image: 'SFX.png', description: ''),
  GameConsole(title: 'SG1000', image: 'SG1000.png', description: ''),
  GameConsole(title: 'SGB', image: 'SGB.png', description: ''),
  GameConsole(title: 'SUFAMI', image: 'SUFAMI.png', description: ''),
  GameConsole(title: 'SUPERVISION', image: 'SUPERVISION.png', description: ''),
  GameConsole(title: 'SUPERVISION-alt', image: 'SUPERVISION-alt.png', description: ''),
  GameConsole(title: 'THOMSON', image: 'THOMSON.png', description: ''),
  GameConsole(title: 'TI83', image: 'TI83.png', description: ''),
  GameConsole(title: 'TIC', image: 'TIC.png', description: ''),
  GameConsole(title: 'TYRQUAKE', image: 'TYRQUAKE.png', description: ''),
  GameConsole(title: 'UZEBOX', image: 'UZEBOX.png', description: ''),
  GameConsole(title: 'VB', image: 'VB.png', description: ''),
  GameConsole(title: 'VECTREX', image: 'VECTREX.png', description: ''),
  GameConsole(title: 'VIC20', image: 'VIC20.png', description: ''),
  GameConsole(title: 'VIDEOPAC', image: 'VIDEOPAC.png', description: ''),
  GameConsole(title: 'VIDEOPAC-alt', image: 'VIDEOPAC-alt.png', description: ''),
  GameConsole(title: 'VIDEOS', image: 'VIDEOS.png', description: ''),
  GameConsole(title: 'VIDEOTON', image: 'VIDEOTON.png', description: ''),
  GameConsole(title: 'VMAC', image: 'VMAC.png', description: ''),
  GameConsole(title: 'WS', image: 'WS.png', description: ''),
  GameConsole(title: 'WSC', image: 'WSC.png', description: ''),
  GameConsole(title: 'X1', image: 'X1.png', description: ''),
  GameConsole(title: 'X68000', image: 'X68000.png', description: ''),
  GameConsole(title: 'XRICK', image: 'XRICK.png', description: ''),
  GameConsole(title: 'ZXS', image: 'ZXS.png', description: ''),
];
